### ISSUE TITLE
String format error in views/edit_translation.py

### ISSUE THREAD

**Issue by brookzhcn** [wagtail/wagtail-localize#226]
there is a bug in row 420.
'lastPublishedDate': last_published_at.strftime('%-d %B %Y') if last_published_at is not None else None

should be change to 'lastPublishedDate': last_published_at.strftime('%d %B %Y') if last_published_at is not None else None

**Comment by brookzhcn** [comment]
The error also hapens in models.py DATE_FORMAT = '%-d %B %Y'

**Comment by Warqus** [comment]
+1

**Comment by kaedroho** [comment]
Please can you post the error that's being raised? This date format is perfectly valid for me.

The `-` character in `%-d` removes the zero prefix on the day:

 - ``'%-d %B %Y`` returns ``6 November 2020``
 - ``%d %B %Y'`` returns ``06 November 2020``

**Comment by Warqus** [comment]
```
Internal Server Error: /pages/4/edit/
Traceback (most recent call last):
  File "C:\virtual_env\name\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\virtual_env\name\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\virtual_env\name\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\views\pages\edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\views\generic.py", line 60, in run_hook
    result = fn(*args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\wagtail_hooks.py", line 137, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\views\edit_translation.py", line 420, in edit_translation
    'lastPublishedDate': last_published_at.strftime('%-d %B %Y') if last_published_at is not None else None,
ValueError: Invalid format string
```

**Comment by Warqus** [comment]
Not the whole traceback, but same error in models:

```
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\models.py", line 1047, in get_comment
    return _("Translated manually on {date}").format(date=self.updated_at.strftime(DATE_FORMAT))
ValueError: Invalid format string
```

**Comment by kaedroho** [comment]
Oh, that's interesting, thanks! What's your Python version?

**Comment by Warqus** [comment]
Python 3.7.6

**Comment by brookzhcn** [comment]
Python 3.8.1

**Comment by kaedroho** [comment]
Looks like this is a problem with Python on Windows. Python uses the string formatting of the OS and Windows doesn't support `%-d`
https://stackoverflow.com/questions/10807164/python-time-formatting-different-in-windows

We could work around this one by doing the formatting in JavaScript instead. But I still couldn't guarentee Windows support since we don't have a CI environment for it.

Personally, I'd suggest using a VM or WSL2 for Wagtail development, as Wagtail itself doesn't officially support Windows either.

**Comment by Warqus** [comment]
@kaedroho Why not change it to "%d %B %Y", I get that the zero will be displayed then, but does that matter?

**Comment by kaedroho** [comment]
I think it does, Wagtail Localize displays dates next to every single segment so this format will appear a lot of times.

I'd prefer to do this with JavaScript, or find some other way to format dates that doesn't depend on the platform the Python code is running on.
