### ISSUE TITLE
Error while trying to open translated page to edit

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail-localize#227]
I am trying to edit a translated page and got this error:

```
Internal Server Error: /pages/6/edit/
Traceback (most recent call last):
  File "C:\virtual_env\name\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\virtual_env\name\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\virtual_env\name\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\auth.py", line 191, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\views\pages\edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "C:\virtual_env\name\lib\site-packages\wagtail\admin\views\generic.py", line 60, in run_hook
    result = fn(*args, **kwargs)
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\wagtail_hooks.py", line 137, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\views\edit_translation.py", line 395, in edit_translation
    for segment in string_segments
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\views\edit_translation.py", line 395, in <listcomp>
    for segment in string_segments
  File "C:\virtual_env\name\lib\site-packages\wagtail_localize\views\edit_translation.py", line 229, in get_segment_location_info
    block_field = block_type.child_blocks[block_field_name].label
AttributeError: 'CharBlock' object has no attribute 'child_blocks'
```

**Comment by Syltas** [comment]
+1

**Comment by kaedroho** [comment]
Thanks for reporting! Looks like it's breaking where it's looking for translatable segments in a streamfield. Would it be possible to share the streamfield definition of the page that is broken?

**Comment by Syltas** [comment]
In my case it's:
`content = StreamField(
        [
            ("lead", streamblocks.LeadBlock()),
            ("heading", streamblocks.HeadingBlock()),
            ("full_richtext", streamblocks.RichtextBlock()),
            ("image_caption", streamblocks.ImageAndSubcaptionBlock()),
            ("image", ImageChooserBlock()),
        ],
        null=True,
        blank=True,
    )`

Where streamblocks are my custom blocks:

`class LeadBlock(blocks.StructBlock):
    """Better styled intro text"""

    text = blocks.TextBlock(required=True, help_text="Add an intro")

    class Meta: # noqa
        template = "streams/lead_block.html"
        icon = "doc-empty"
        label = "Lead"

class HeadingBlock(blocks.StructBlock):
    """Nice styled headings"""

    text = blocks.CharBlock(required=True, help_text="Cool heading")

    class Meta: #noqa
        template = "streams/heading_block.html"
        icon = "doc-empty"
        label = "Heading"

class ImageAndSubcaptionBlock(blocks.StructBlock):
    """Image and subcaption for references."""

    image = ImageChooserBlock(required=True, help_text="Add your image")
    subcaption = blocks.CharBlock(required=True, help_text="Add caption/reference")

    class Meta:  # noqa
        template = "streams/image_and_subcaption_block.html"
        icon = "image"
        label = "Image & Subcaption"`

**Comment by brookzhcn** [comment]
+1  AttributeError: 'RichTextBlock' object has no attribute 'child_blocks'

**Comment by Warqus** [comment]
@kaedroho My streamfield is quite complex with many different components and files. I think the following is where it went wrong:

```
StreamField(
        [
            ('rich_text', app_cms_blocks_custom.CustomBackgroundTitleBlock(
                [
                    ('width', blocks.ChoiceBlock(
                        choices=[
                            (None, _('Inherit')),
                            ('sm', _('Small')),
                            ('md', _('Medium')),
                            ('lg', _('Large')),
                        ],
                        default=None,
                        required=False,
                        icon='list-ul')
                     ),
                    ('text', app_cms_blocks_custom.CustomRichTextBlock()),
                ],
                icon='doc-full'
            ))
            ...other features in streamfield
```

with the following:

```
class CustomBackgroundTitleBlock(blocks.StructBlock):
    background = blocks.BooleanBlock(
        required=False,
        default=False,
        help_text=_('if true, the background will be gray.')
    )
    title = blocks.CharBlock(max_length=100, required=False)
```

and:

```
class CustomRichTextBlock(blocks.RichTextBlock):
    def get_api_representation(self, value, context=None):
        representation = super().get_api_representation(value, context)

        return expand_db_html(representation)
```
