### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by brookzhcn** [wagtail/wagtail-localize#228]
Row 88 function is_empty

wagtail_localize/segments/types.py

may change to:
```
def is_empty(self):
      if self.string is not None:
          return self.string.data in ["", None]
      return False
```

**Comment by brookzhcn** [comment]
same error occure in when stringvalue=None

wagtail_localize/models.py
`
    @classmethod
    def from_value(cls, locale, stringvalue):
        string, created = cls.objects.get_or_create(
            locale_id=pk(locale),
            data_hash=cls.get_data_hash(stringvalue.data),
            defaults={"data": stringvalue.data},
        )

        return string
`

**Comment by kaedroho** [comment]
Thanks for reporting! It definitely looks like there's a bug somewhere, but I don't think it's with the code you've referenced above as ``None`` isn't a valid value to have in either case.

Please could you provide some instructions for reproducing the problem you encountered? Also, a traceback would be really useful.

**Comment by Shaffle1** [comment]
Hello @kaedroho, @brookzhcn! Same error...
Here's traceback:
```
Traceback (most recent call last):
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail\admin\auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\views\submit_translations.py", line 181, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\views\submit_translations.py", line 145, in post
    translator.create_translations(self.object)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\views\submit_translations.py", line 77, in create_translations
    source, created = TranslationSource.get_or_create_from_instance(instance)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\models.py", line 210, in get_or_create_from_instance
    source.refresh_segments()
  File "c:\users\shaffle\appdata\local\programs\python\python38-32\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\models.py", line 333, in refresh_segments
    for segment in extract_segments(self.as_instance()):
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\segments\extract.py", line 194, in extract_segments
    return [
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\segments\extract.py", line 197, in <listcomp>
    if not segment.is_empty()
  File "C:\Users\Shaffle\.virtualenvs\mistralvision-Qp0hboiu\lib\site-packages\wagtail_localize\segments\types.py", line 89, in is_empty
    return self.string.data in ["", None]

Exception Type: AttributeError at /admin/localize/submit/page/3/
Exception Value: 'NoneType' object has no attribute 'data'
```

Didn't do anything, just installed `wagtail-localize` latest, configured `LANGUAGES`, when I tried to add translate homepage to other languages, I've checked any language, pressed Next and this error occured...

Hope this helps, I love your approach to Internationalisation, fix it, please.

**Comment by kaedroho** [comment]
Thanks for the traceback! It looks to me like it extracted a ``None`` value from a text field, which is not something I've tested for in the past.

Should be a simple fix, we just need to check if the field is `None`` before extracting a segment from it.

**Comment by Shaffle1** [comment]
Excellent! Waiting for the update then.

**Comment by patillacode** [comment]
Sorry to bump this closed issue @kaedroho , but I believe this wasn't completely fixed.

As OP mentions in the first message the function `is_empty` should also be addressed:
#89 in `segments/types.py` does not contemplate `self.string`  being `None` itself.

```python
def is_empty(self):
        return self.string.data in ["", None]
```

I was able to replicate the exact same behaviour and error and after changing the mentioned code to the following, did the trick for me:

```python
def is_empty(self):
        return True if not self.string else self.string.data in ["", None]
```

Sorry again if this wasn't the way to inform about it

**Comment by kaedroho** [comment]
Thanks for reporting!

A ``StringValue`` with null string is invalid, so the code that's constructing that ``StringValue`` is at fault here.

I'll reopen this to add a null check into the constructor, that should bring the real issue into the light.
