### ISSUE TITLE
Error when trying to translate Snippet

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail-localize#233]
Whenever I created an English snippet and I am trying to translate it to another language I get the following error:

<details>
<summary>Traceback</summary>

```
Internal Server Error: /localize/submit/snippet/app_cms/snippetheader/1/
Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "app_cms_snippetheader_name_key"
DETAIL:  Key (name)=(Test English) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\submit_translations.py", line 181, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\submit_translations.py", line 145, in post
    translator.create_translations(self.object)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\views\submit_translations.py", line 103, in create_translations
    translation.save_target(user=self.user)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\models.py", line 833, in save_target
    self.source.create_or_update_translation(self.target_locale, user=user, publish=publish, fallback=True, copy_parent_pages=True)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\models.py", line 513, in create_or_update_translation
    translation.save()
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Work\virtual_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Work\virtual_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "app_cms_snippetheader_name_key"
DETAIL:  Key (name)=(Test English) already exists.
```
</details>

this is the Meta of my snippet:

```
    class Meta(TranslatableMixin.Meta):
        verbose_name = _('header')
        verbose_name_plural = _('headers')

        unique_together = [('translation_key', 'locale')]
```

**Comment by kaedroho** [comment]
It looks like you've added a unique key field to your name field. There's not much we can do about this in Wagtail localize, I'd suggest turning this into a `unique_together` constraint on ``('locale', 'name')`` instead if that's possible.

I'll leave this open since I think we should document this caveat somewhere.

**Comment by Warqus** [comment]
Thanks! This was indeed the case.

**Comment by kaedroho** [comment]
No problem!

Also, thanks for all your reports so far, it's really useful to get this feedback before the release

**Comment by Warqus** [comment]
I appreciate all the work you (and the wagtail team) put into this! 👍

**Comment by zerolab** [comment]
hey @Warqus will close in favour of #484 which has further information.
Thank you
