### ISSUE TITLE
No exception message supplied

### ISSUE THREAD

**Issue by Syltas** [wagtail/wagtail-localize#242]
When I try to translate my page with custom snippets I get the following error: No exception message supplied
Traceback:

`Environment:

Request Method: POST
Request URL: http://localhost:8000/admin/localize/submit/page/19/?next=%2Fadmin%2Fpages%2F4%2F

Django Version: 3.1.3
Python Version: 3.7.3
Installed Applications:
['home',
 'search',
 'flex',
 'streams',
 'site_settings',
 'subscribers',
 'blog',
 'menus',
 'contact',
 'core',
 'wagtail.contrib.forms',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.redirects',
 'wagtail.contrib.settings',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.sitemaps',
 'wagtail.contrib.postgres_search',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.api.v2',
 'wagtail_localize',
 'wagtail_localize.locales',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'captcha',
 'wagtailcaptcha',
 'rest_framework',
 'corsheaders',
 'django_social_share',
 'el_pagination',
 'compressor',
 'django_extensions',
 'wagtail.contrib.styleguide']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']

Traceback (most recent call last):
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/views/submit_translations.py", line 193, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/views/submit_translations.py", line 157, in post
    translator.create_translations(self.object)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/views/submit_translations.py", line 83, in create_translations
    source, created = TranslationSource.get_or_create_from_instance(instance)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/models.py", line 214, in get_or_create_from_instance
    source.refresh_segments()
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/models.py", line 337, in refresh_segments
    for segment in extract_segments(self.as_instance()):
  File "/home/commander_andrew/.local/lib/python3.7/site-packages/wagtail_localize/segments/extract.py", line 156, in extract_segments
    raise Exception

Exception Type: Exception at /admin/localize/submit/page/19/
Exception Value: `

I tried removing all snippets (in case they were the problem) to see where the problem could be but I wasn't able to solve the exception.

**Comment by Syltas** [comment]
Found the problem 🤦
I had an ArticleBlogPage extending a BlogDetailPage and I defined the banner image as synchronized field in the BlogDetailPage but as translatable field in the ArticleBlogPage
Hope that helps (:
