### ISSUE TITLE
Adding invalid link identifier in translated block that does not exist in the source raise 500 errors while saving page

### ISSUE THREAD

**Issue by mardiros** [wagtail/wagtail-localize#294]
The following block should be marked as invalid and saving should be forbidden instead of raising the following traceback.

![image](https://user-images.githubusercontent.com/447396/103407040-4f55d900-4b5d-11eb-8781-82e14b176fa5.png)

```
[2020-12-31 10:40:26,248][624][ERROR][gn.home.management.commands.import_tld_translations] Error while processing skin
Traceback (most recent call last):
  File "/app/gn/home/management/commands/import_tld_translations.py", line 500, in handle
    tld_info, tld_page, locale, override=override, style=self.style,
  File "/app/gn/home/management/commands/import_tld_translations.py", line 464, in create_tld_translation_page
    translation.save_target(user, publish=True)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/models.py", line 863, in save_target
    self.source.create_or_update_translation(self.target_locale, user=user, publish=publish, fallback=True, copy_parent_pages=True)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/models.py", line 504, in create_or_update_translation
    ingest_segments(original, translation, self.locale, locale, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 168, in ingest_segments
    ).handle_stream_block(data, field_segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 144, in handle_stream_block
    block.value = self.handle_block(block.block, block.value, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 80, in handle_block
    return self.handle_struct_block(block_value, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 112, in handle_struct_block
    block_type, block_value, segments
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 86, in handle_block
    return self.handle_stream_block(block_value, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 144, in handle_stream_block
    block.value = self.handle_block(block.block, block.value, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 80, in handle_block
    return self.handle_struct_block(block_value, segments)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 112, in handle_struct_block
    block_type, block_value, segments
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/segments/ingest.py", line 74, in handle_block
    return RichText(restore_strings(template, strings))
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/strings.py", line 393, in restore_strings
    text_element.replaceWith(string.render_soup(attrs))
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/strings.py", line 176, in render_soup
    walk(soup)
  File "/usr/local/lib/python3.7/site-packages/wagtail_localize/strings.py", line 171, in walk
    element.attrs = attrs[element.attrs['id']]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kaedroho** [comment]
Fixed by https://github.com/wagtail/wagtail-localize/pull/295
