### ISSUE TITLE
Error when trying to translate page

### ISSUE THREAD

**Issue by ceelian** [wagtail/wagtail-localize#298]
I get the following error when trying to translate a page via the wagtail admin. Any Ideas what this might cause?

wagtail==2.11.3
wagtail-localize==0.9.4

```
[09/Jan/2021 14:01:28] "GET /cms/localize/submit/page/36/?next=%2Fcms%2Fpages%2F34%2F HTTP/1.0" 200 16927
Internal Server Error: /cms/localize/submit/page/36/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 193, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 157, in post
    translator.create_translations(self.object)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 83, in create_translations
    source, created = TranslationSource.get_or_create_from_instance(instance)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/models.py", line 214, in get_or_create_from_instance
    source.refresh_segments()
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/models.py", line 337, in refresh_segments
    for segment in extract_segments(self.as_instance()):
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 130, in extract_segments
    for segment in StreamFieldSegmentExtractor(field, include_overridables=is_synchronized).handle_stream_block(
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 103, in handle_stream_block
    for segment in self.handle_block(block.block, block.value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 56, in handle_block
    return self.handle_struct_block(block_value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 88, in handle_struct_block
    for segment in self.handle_block(block_type, block_value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 43, in handle_block
    return [StringSegmentValue("", block_value)]
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/types.py", line 71, in __init__
    raise TypeError("`string` must be either a `StringValue` or a `str`. Got `{}`".format(type(string).__name__))
TypeError: `string` must be either a `StringValue` or a `str`. Got `NoneType`
ERROR 2021-01-09 14:01:33,066 | 2514 140082901228320 | log.py:224 | Internal Server Error: /cms/localize/submit/page/36/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 193, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 157, in post
    translator.create_translations(self.object)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/views/submit_translations.py", line 83, in create_translations
    source, created = TranslationSource.get_or_create_from_instance(instance)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/models.py", line 214, in get_or_create_from_instance
    source.refresh_segments()
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/models.py", line 337, in refresh_segments
    for segment in extract_segments(self.as_instance()):
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 130, in extract_segments
    for segment in StreamFieldSegmentExtractor(field, include_overridables=is_synchronized).handle_stream_block(
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 103, in handle_stream_block
    for segment in self.handle_block(block.block, block.value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 56, in handle_block
    return self.handle_struct_block(block_value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 88, in handle_struct_block
    for segment in self.handle_block(block_type, block_value)
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/extract.py", line 43, in handle_block
    return [StringSegmentValue("", block_value)]
  File "/usr/local/lib/python3.8/site-packages/wagtail_localize/segments/types.py", line 71, in __init__
    raise TypeError("`string` must be either a `StringValue` or a `str`. Got `{}`".format(type(string).__name__))
TypeError: `string` must be either a `StringValue` or a `str`. Got `NoneType`
[09/Jan/2021 14:01:33] "POST /cms/localize/submit/page/36/?next=%2Fcms%2Fpages%2F34%2F HTTP/1.0" 500 174339

```

**Comment by ceelian** [comment]
I could figure out the root cause: it happens when we create a page programmatically (this is how we bootstrap a wagtail example website for our SaaS Kit). We usually create pages like this:

```
page = MyPage(title="Foo", slug="foo", show_in_menus=True)
page.body.is_lazy = True
page.body.stream_data = [
    {
        "type": "hero",
        "value": {
            "background_color": "primary-A100",   # <-- if one or more fields fron the models (with defaults) are missing it fails
            "background_image": images['bg-elements.png'],
            "primary_content": [
                {
                    "type": "headline",
                    "value": "My headline",
                    "id":"d9063835-981e-4df7-bbdc-9b33c5aa3b18" # <-- if id field is missing it fails as well
                },

            ],
        },
    }
]
home_page_en.add_child(instance=page)
```

In our code we didn't provide all custom fields in the stream_data which were good with the default values for us. Nor did we set the uuid as I assumed that with the `is_lazy=True` (source https://github.com/wagtail/wagtail/issues/2110#issuecomment-171657426) the json is deserialized and missing fields/uuid are filled according to the defaults.

It worked that way with our existing setup (wagtail 2.10.3, wagtailtrans 2.2.1) but since migrating to wagtail-localize 0.9.4 and wagtail 2.11.3 wagtail-localize throws the previous mentioned error. 

My conclusion, either this way of adding pages programmatically was wrong from the beginning and it was "luck" that it worked in previous version or wagtail-localize is stricter in terms of stream_fields (intentionally or because of a bug).

We worked around this issue by adding all fields and a newly generated uuid4 to each block but it would be great to get some feedback if this is a bug, a feature or if we should create pages programmatically in a different way. Thx.

**Comment by kmtracey** [comment]
This can also happen with UI-created pages, IF a field is added to a stream block after the the page is initially created/saved. Simply re-saving the page in cms admin fixes the missing data that causes the 500 error (in the case where I encountered this).
