### ISSUE TITLE
sync_git crashes when a commit is pushed to the repo right after it gets pulled by wagtail-localize

### ISSUE THREAD

**Issue by TheoChevalier** [wagtail/wagtail-localize#435]
When Pontoon commits to the repository ***while*** `sync_git` is running (after the initial pull, and before the push), it prevents wagtail-localize from committing changes to the repository because the head commit is now different.
The next time `sync_git` runs, this happens:

```
INFO - Pulling repository
Traceback (most recent call last):
  File "network-api/manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/management/commands/sync_git.py", line 19, in handle
    SyncManager(logger=logger).sync()
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 165, in sync
    _pull(repo, self.logger)
  File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/sync.py", line 34, in _pull
    last_commit_id, current_commit_id
  File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize_git/git.py", line 50, in get_changed_files
    new_commit, old_commit
_pygit2.GitError: object not found - no match for id (b2c0f73ae4e6dd4ec4d247225bb243b1d7b2a159)
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

```

I’ve hit the issue 3 times, so it seems to be reproducible

The current workaround is to run 
`DELETE FROM wagtail_localize_git_synclogresource;`
`DELETE FROM wagtail_localize_git_synclog;`

**Comment by phildexter** [comment]
Notes: 

Solution: try to find common commit that can be used
Solution: put the whole thing in a transaction
