### ISSUE TITLE
not working with wagtail 2.16.x?

### ISSUE THREAD

**Issue by maxodoble** [wagtail/wagtail-localize#519]
Hi,

i tried to use wagtail localize with a brand new wagtail 2.16.1 installation:

- installed wagtail localize from the main branch of this repo.
- installed wagtail 2.16.1
- followed the tutorial from wagtail localize
- configured locales "german" (main  locale) and "english"

all seemed to work o.k, until i try to translate the german homepage to english (Click on "Translate this page" > choose locale > submit):

```
Environment:

Request Method: POST
Request URL: http://localhost:8000/admin/localize/submit/page/3/?next=%2Fadmin%2Fpages%2F

Django Version: 4.0.2
Python Version: 3.10.2
Installed Applications:
['home',
 'search',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail_localize/views/submit_translations.py", line 235, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail_localize/views/submit_translations.py", line 190, in post
    return self.form_valid(form)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 78, in inner
    with self._recreate_cm():
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/db/transaction.py", line 290, in __exit__
    connection.set_autocommit(True)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/db/backends/base/base.py", line 431, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/db/backends/base/base.py", line 664, in run_and_clear_commit_hooks
    func()
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/core/models/__init__.py", line 510, in <lambda>
    transaction.on_commit(lambda: page_slug_changed.send(
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 170, in send
    return [
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 171, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/contrib/redirects/signal_handlers.py", line 49, in autocreate_redirects_on_slug_change
    create_redirects(page=instance, page_old=instance_before, sites=sites)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/contrib/redirects/signal_handlers.py", line 127, in create_redirects
    old_urls = _page_urls_for_sites(page_old, sites, cache_target=page)
  File "/Users/hra/venvs/wt216/lib/python3.10/site-packages/wagtail/contrib/redirects/signal_handlers.py", line 98, in _page_urls_for_sites
    site_id, root_url, page_path = page.get_url_parts(request)

Exception Type: TypeError at /admin/localize/submit/page/3/
Exception Value: cannot unpack non-iterable NoneType object
```

Same procedure is working o.k for me when using wagtail 2.15.x and latest release of wagtail localize.

Any idea?

**Comment by zerolab** [comment]
are your site entries configured correctly? it looks like `page.get_url_parts(request)` returns `None`

Looking further, the only part that does so in `page.get_url_parts()` is

```python
        possible_sites = self._get_relevant_site_root_paths(request)

        if not possible_sites:
            return None
```

and `_get_relevant_site_root_paths()` was added in 2.16

This is core bug as far as I can tell. 
Does it work if you set `WAGTAILREDIRECTS_AUTO_CREATE = False` in your settings?

**Comment by maxodoble** [comment]
> 
> This is core bug as far as I can tell. Does it work if you set `WAGTAILREDIRECTS_AUTO_CREATE = False` in your settings?

with `WAGTAILREDIRECTS_AUTO_CREATE = False` in the settings, i am not getting the above error when trying to submit the translation, but then the translated page is just empty, without any fields at all. and the translated page stays empty when trying to edit the translated page.

No problems when editing the source page.

Max

**Comment by maxodoble** [comment]
o.k,

the white translated page was obviously an error on my side, because the static resources weren't built when i manually installed wagtail-localize with `pip install` from the downloaded sources.

by manually building these resources, the white page is gone and the fields for translation are available now!

`WAGTAILREDIRECTS_AUTO_CREATE = False`is still necessary though?

Thanks,
Max

**Comment by zerolab** [comment]
Hey Max,

It is difficult to undertand the exact circumstances for why you get the error. It is possible you have a mismatched `Site` record. i.e. it is configured for `something.com` and you're accessing it via `localhost` or `something.org`.

`WAGTAILREDIRECTS_AUTO_CREATE = False` ensures the signal to autocreate the redirect doesn't fire.

I can't replicate the issue locally either. Will open a PR against Wagtail core so `page.get_url_parts()` returns the correct number of variables when it can't find any `possible_sites`

**Comment by zerolab** [comment]
Will close in favour of https://github.com/wagtail/wagtail/issues/7999

**Comment by zerolab** [comment]
@maxodoble do you have your sites properly defined in `Settings > Sites`?
Are your models doing anything uncommon (e.g. using routable mixin, overriding any of the url methods)?

**Comment by zerolab** [comment]
Alright, this will make it in 2.16.2 which comes out today/tomorrow
