### ISSUE TITLE
Can't create translation for Home page

### ISSUE THREAD

**Issue by francuz08011990** [wagtail/wagtail-localize#556]
Hi,
i updated wagtail to v2.16.2, wagtail-localize==1.1.1 and i have a problem. I can't translate Home page on the new locale.

```
[2022-04-13 13:50:31] [ERROR] [dev]:Internal Server Error: /admin/localize/submit/page/3/
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
return callback(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
return view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 242, in dispatch
return super().dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 190, in post
return self.form_valid(form)
File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
return func(*args, **kwds)
File "/usr/local/lib/python3.9/site-packages/wagtail_localize/views/submit_translations.py", line 216, in form_valid
single_translated_object = self.object.get_translation(
File "/usr/local/lib/python3.9/site-packages/wagtail/core/models/i18n.py", line 152, in get_translation
return self.get_translations(inclusive=True).get(locale_id=pk(locale))
File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
raise self.model.DoesNotExist(
apps.home.models.HomePage.DoesNotExist: HomePage matching query does not exist.
```

Everything was ok before the update wagtail & wagtail-localize.
Versions before: wagtail==2.15.1, wagtail-localize==1.0.1

Maybe someone had such a problem.
Thanks for your help !

**Comment by francuz08011990** [comment]
The problem was solved !
Previously, the translation of the main page (Home page) could be done and it was automatically created.

Now I had to create a translation of the subpage, and then translate its parent (Home page)
