### ISSUE TITLE
As of Wagtail 5.2 PagePreviewSidePanel was renamed into PreviewSidePanel. And some other classes removed. 

### ISSUE THREAD

**Issue by universewithtin** [wagtail/wagtail-localize#741]
I know that **wagtail-localize 1.6** described to work on **wagtail 5.0**, so i would just note it here for anyone seeking.

As for **Wagtail 5.2** some classes are removed or renamed. 
Namely, **_'PagePreviewSidePanel'_** was removed according to [this changelogs](https://docs.wagtail.org/en/latest/releases/5.2.html#basesidepanels-pagesidepanels-and-snippetsidepanels-classes-are-removed).
**wagtail-localize 1.6** by October 7th does have those classes used, but **wagtail 5.2** released three weeks later, thus have new class names.
_**PageSidePanels**_ is the other one to cause error too.

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\nurmu\AppData\Local\Programs\Python\Python311\Lib\[threading.py](http://threading.py/)", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\nurmu\AppData\Local\Programs\Python\Python311\Lib\[threading.py](http://threading.py/)", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\utils\[autoreload.py](http://autoreload.py/)", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\core\management\commands\[runserver.py](http://runserver.py/)", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\core\management\[base.py](http://base.py/)", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\core\checks\[registry.py](http://registry.py/)", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\core\checks\[urls.py](http://urls.py/)", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\core\checks\[urls.py](http://urls.py/)", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\urls\[resolvers.py](http://resolvers.py/)", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\utils\[functional.py](http://functional.py/)", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\urls\[resolvers.py](http://resolvers.py/)", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\utils\[functional.py](http://functional.py/)", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\django\urls\[resolvers.py](http://resolvers.py/)", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\AppData\Local\Programs\Python\Python311\Lib\importlib\[__init__.py](http://__init__.py/)", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nurmu\Videos\qazanat\qazanatkz\[urls.py](http://urls.py/)", line 5, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\admin\urls\[__init__.py](http://__init__.py/)", line 13, in <module>
    from wagtail.admin.api import urls as api_urls
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\admin\api\[urls.py](http://urls.py/)", line 11, in <module>
    for fn in hooks.get_hooks("construct_admin_api"):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\[hooks.py](http://hooks.py/)", line 112, in get_hooks
    search_for_hooks()
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\[hooks.py](http://hooks.py/)", line 106, in search_for_hooks
    list(get_app_submodules("wagtail_hooks"))
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\utils\[apps.py](http://apps.py/)", line 23, in get_app_submodules
    yield name, import_module(f"{name}.{submodule_name}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\AppData\Local\Programs\Python\Python311\Lib\importlib\[__init__.py](http://__init__.py/)", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail_localize\[wagtail_hooks.py](http://wagtail_hooks.py/)", line 23, in <module>
    from .views import (
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail_localize\views\[edit_translation.py](http://edit_translation.py/)", line 63, in <module>
    from wagtail_localize.side_panels import LocalizedPageSidePanels
  File "C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail_localize\[side_panels.py](http://side_panels.py/)", line 2, in <module>
    from wagtail.admin.ui.side_panels import PagePreviewSidePanel, PageSidePanels
ImportError: cannot import name 'PagePreviewSidePanel' from 'wagtail.admin.ui.side_panels' (C:\Users\nurmu\Videos\qazanat\env\Lib\site-packages\wagtail\admin\ui\side_panels.py)
```

**Comment by zerolab** [comment]
See https://github.com/wagtail/wagtail-localize/issues/740#issuecomment-1801488957
