### ISSUE TITLE
Can't translate the page  "table wagtail_localize_translationlog has no column named page_revision_id"

### ISSUE THREAD

**Issue by jacksylyk** [wagtail/wagtail-localize#804]
Traceback
```

Request Method: POST
Request URL: http://localhost:8000/admin/localize/submit/page/3/

Installed Applications:
['home',
 'search',
 'shops',
 'production',
 'aboutus',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail_localize',
 'wagtail_localize.locales',
 'wagtail',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)

The above exception (table wagtail_localize_translationlog has no column named page_revision_id) was the direct cause of the following exception:
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 173, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail/admin/auth.py", line 165, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/views/submit_translations.py", line 174, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/views/submit_translations.py", line 118, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/views/submit_translations.py", line 125, in form_valid
    translate_object(
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/operations.py", line 101, in translate_object
    translator.create_translations(instance)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/operations.py", line 90, in create_translations
    translation.save_target(user=self.user, publish=publish)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/models.py", line 1341, in save_target
    self.source.create_or_update_translation(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/wagtail_localize/models.py", line 858, in create_or_update_translation
    TranslationLog.objects.create(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/website/cumanwebcms/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)

Exception Type: OperationalError at /admin/localize/submit/page/3/
Exception Value: table wagtail_localize_translationlog has no column named page_revision_id
```
wagtail-localize 1.8.1
wagtail 5.2
Django Version: 4.2.7
Python Version: 3.10.12

And another question: is it possible to forcefully remove a locale? Because when I delete the locale it doesn’t work for me since there are pages that use this locale. But these pages are not visible to me

**Comment by zerolab** [comment]
Are you sure you're on wagtail-localize 1.8.x? Did you at any point upgrade to 1.9.x? Askin as 
`TranslationLog`s `page_revision` field was renamed to `revision` in v1.9

You can find pages that use a specific locale with something like `Page.objects.filter(locale__language_code="fr")` ("fr" being the language code as defined in settings) or `Page.objects.filter(locale=2)` (substitute 2 with the actual Locale object id)

**Comment by jacksylyk** [comment]
Thanks a lot. After I updated to 1.9 the translations started working.
